version: "3.7"
services:

  app:
    container_name: notification_admin_api
    restart: unless-stopped
    image: notification_admin_image
    build:
      context: .
    networks:
      - backend
    ports:
      - "80:8000"

networks:
  backend:
    external: true
